// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Modal: typeof import('./components/Modal.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesonForm: typeof import('./components/Saleson/SalesonForm.vue')['default']
    SalesonRow: typeof import('./components/Saleson/SalesonRow.vue')['default']
    SalesonTable: typeof import('./components/Saleson/SalesonTable.vue')['default']
  }
}

export {}
